services:
    web:
        build: .
        container_name: devgrid-weather-challenge
        ports:
            - "8000:8000"
        volumes:
            - .:/app
        environment:
            - DATABASE_URL=sqlite:///./test.db

        command: uvicorn src.main:app --host 0.0.0.0 --port 8000

    tests:
        build: .
        volumes:
            - .:/app
        depends_on:
            - web
        command: pytest -p no:warnings

    coverage:
        build: .
        volumes:
            - .:/app
        depends_on:
            - web
        command: pytest --cov=. --cov-report=html -p no:warnings
